### PR TITLE
New rewriteArrayElements function

### PR DESCRIPTION
**Pull request by newhoggy**
The `rewriteArrayElements` can be used to rewrite `configuration.yaml` in test code.

For example we do something similar with `rewriteObject` [here](https://github.com/input-output-hk/cardano-node/blob/2b1d18c6c7b7142d9eebfec34da48840ed4409b6/cardano-testnet/src/Testnet/Cardano.hs#L244).

### CODE REVIEW

**Comment by newhoggy** [comment]
Looks like `cardano-base` works with both versions of `aeson` anyway.

**Review by Jimbo4350 — DISMISSED** [review]
The ability to specify the config yaml file should result in us not needing to rewrite the config yaml file. Re-writing the config yaml file before it is used will be confusing for users because it won't be obvious that the exact config yaml file they specified isn't being used. If we need to re-write anything in the config yaml file then this is an indication that we need to modify the input the config yaml file.

**Comment by newhoggy** [comment]
> The ability to specify the config yaml file should result in us not needing to rewrite the config yaml file. Re-writing the config yaml file before it is used will be confusing for users because it won't be obvious that the exact config yaml file they specified isn't being used. If we need to re-write anything in the config yaml file then this is an indication that we need to modify the input the config yaml file.

You raise an important point.

We already rewrite the yaml file and we do this because sometimes it is convenient to make the way the testnet is brought up to be configuration.

The `cardano-testnet` executable does this to spin up a testnet from the command line.

But we should rewrite the yaml file less than we already do, which means the way we set up the testnet needs to changed and the code that rewrites the yaml needs to move out so that tests have the option of not rewriting the yaml at all.

I would still like this change for cases where to rewriting might be desired for example in the `cardano-testnet` executable, or if there are any tests that want to parameterise over testnet configuration.

Separately we need a to move the rewriting code in `Testnet.Cardano` elsewhere.

**Review by Jimbo4350 — APPROVED** [review]

**Comment by cblp** [comment]
This function is not needed, it makes an opaque level of abstraction where a transparency is needed. Explicit lambdacase would be better, or lensy `_Array . each %~ f`

**Comment by newhoggy** [comment]
> This function is not needed, it makes an opaque level of abstraction where a transparency is needed. Explicit lambdacase would be better, or lensy `_Array . each %~ f`

I'm fine with lenses, but we currently have a policy of no lenses.

**Comment by cblp** [comment]
Explicit lambdacase is stell better than an opaque function

**Pull request merged**
